BINS=bin/ats-client bin/ats-auto
SCRIPTS=scripts/ats-client-functions scripts/functions 
LOGGERS=scripts/loggers/debug-logger scripts/loggers/txt-logger 
EXAMPLES=examples/searduino.sh

#
# directory setup
#
INSTALL_DIR=__INSTALL_DIR__
SHARE_DIR=__SHARE_DIR__
BIN_DIR=__BIN_DIR__




#
# 
#

$(BINS): bin/ats-client.tmpl  bin/ats-auto.tmpl Makefile
	@echo "*** Creating scripts ***"
	if [ -f bin/ats-client ] ; then mv bin/ats-client bin/ats-client.keep ; fi
	if [ -f bin/ats-auto ]   ; then mv bin/ats-auto   bin/ats-auto.keep   ; fi
	cat bin/ats-client.tmpl | sed "s,__ATS_DIR__,$(INSTALL_DIR),g" > bin/ats-client
	cat bin/ats-auto.tmpl   | sed "s,__ATS_DIR__,$(INSTALL_DIR),g" > bin/ats-auto
	chmod a+x bin/ats-client
	chmod a+x bin/ats-auto

$(EXAMPLES): examples/searduino.tmpl
	@echo "*** Creating examples ***"
	cat examples/searduino.tmpl | sed "s,__ATS_DIR__,$(INSTALL_DIR),g" > examples/searduino.sh
	chmod a+x examples/searduino.sh

install: $(BINS) $(SCRIPTS) $(EXAMPLES) 
	@echo "*** Installing ***"
	mkdir -p $(BIN_DIR)/
	mkdir -p $(SHARE_DIR)/scripts
	mkdir -p $(SHARE_DIR)/scripts/loggers
	mkdir -p $(SHARE_DIR)/examples

	cp $(BINS)        $(BIN_DIR)/
	cp $(EXAMPLES)    $(SHARE_DIR)/examples
	cp -r $(SCRIPTS)  $(SHARE_DIR)/scripts
	cp -r $(LOGGERS)  $(SHARE_DIR)/scripts/loggers

check:
	test/install-and-test-auto.sh


#
# clean 
#
clean:
	rm -f $(BINS) Makefile
