#
#                                                                   
#                   Testing Machine
#                      
#   Copyright (C) 2012, 2013 TIS Innovation Park
#                                                                   
# This program is free software; you can redistribute it and/or     
# modify it under the terms of the GNU General Public License       
# as published by the Free Software Foundation; either version 3    
# of the License, or any later version.                             
#                                                                   
#                                                                   
# This program is distributed in the hope that it will be useful,   
# but WITHOUT ANY WARRANTY; without even the implied warranty of    
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the     
# GNU General Public License for more details.                      
#                                                                   
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software       
# Foundation, Inc., 51 Franklin Street, Boston,            
# MA  02110-1301, USA.                                              
#

TM_VMM=bin/tm-vmm
TM_VMM_AUTO=bin/tm-vmm-auto

TM_VERSION=__TM_VERSION__

BINS=${TM_VMM} ${TM_VMM_AUTO}
SCRIPTS=scripts/vmm-client-functions scripts/functions scripts/generate-conf
LOGGERS=scripts/loggers/debug-logger scripts/loggers/txt-logger 
EXAMPLES=examples/searduino.sh

#
# directory setup
#
INSTALL_DIR=__INSTALL_DIR__
SHARE_DIR=__SHARE_DIR__
BIN_DIR=__BIN_DIR__


DIST_DIR_TMP=testing-machine-$(TM_VERSION)

#
# 
#

$(BINS): ${TM_VMM}.tmpl  ${TM_VMM_AUTO}.tmpl Makefile
	@echo "*** Creating scripts ***"
	if [ -f ${TM_VMM} ] ; then mv ${TM_VMM} ${TM_VMM}.keep ; fi
	if [ -f ${TM_VMM_AUTO} ]   ; then mv ${TM_VMM_AUTO} ${TM_VMM_AUTO}.keep   ; fi
	cat ${TM_VMM}.tmpl | sed "s,__VMM_DIR__,$(INSTALL_DIR),g" > ${TM_VMM}
	cat ${TM_VMM_AUTO}   | sed "s,__VMM_DIR__,$(INSTALL_DIR),g" > ${TM_VMM_AUTO}
	chmod a+x ${TM_VMM}
	chmod a+x ${TM_VMM_AUTO}

$(EXAMPLES): examples/searduino.tmpl
	@echo "*** Creating examples ***"
	cat examples/searduino.tmpl | sed "s,__VMM_DIR__,$(INSTALL_DIR),g" > examples/searduino.sh
	chmod a+x examples/searduino.sh

install: $(BINS) $(SCRIPTS) $(EXAMPLES) 
	@echo "*** Installing ***"
	mkdir -p $(BIN_DIR)/
	mkdir -p $(SHARE_DIR)/scripts
	mkdir -p $(SHARE_DIR)/scripts/loggers
	mkdir -p $(SHARE_DIR)/examples

	cp $(BINS)        $(BIN_DIR)/
	cp $(EXAMPLES)    $(SHARE_DIR)/examples
	cp -r $(SCRIPTS)  $(SHARE_DIR)/scripts
	cp -r $(LOGGERS)  $(SHARE_DIR)/scripts/loggers

	cd doc && make install

check:
	test/install-and-test-auto.sh


dist:
	rm -fr tmp/$(DIST_DIR_TMP)
	mkdir -p  tmp/$(DIST_DIR_TMP)/doc

	make clean
	cd doc && make clean all

	cp -r doc/      tmp/$(DIST_DIR_TMP)/
	cp -r bin/      tmp/$(DIST_DIR_TMP)/
	cp -r examples/ tmp/$(DIST_DIR_TMP)/
	cp -r scripts/  tmp/$(DIST_DIR_TMP)/

	cp configure Makefile.tmpl README.md    tmp/$(DIST_DIR_TMP)/
	
#
# clean 
#
clean:
	rm -f $(BINS) Makefile
