#
#                                                                   
#                   VVM
#                      
#   Copyright (C) 2012, 2013 TIS Innovation Park
#                                                                   
# This program is free software; you can redistribute it and/or     
# modify it under the terms of the GNU General Public License       
# as published by the Free Software Foundation; either version 3    
# of the License, or any later version.                             
#                                                                   
#                                                                   
# This program is distributed in the hope that it will be useful,   
# but WITHOUT ANY WARRANTY; without even the implied warranty of    
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the     
# GNU General Public License for more details.                      
#                                                                   
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software       
# Foundation, Inc., 51 Franklin Street, Boston,            
# MA  02110-1301, USA.                                              
#


#
# directory setup
#
INSTALL_DIR=__INSTALL_DIR__
SHARE_DIR=__SHARE_DIR__
BIN_DIR=__BIN_DIR__


#
# Sources for manuals
#
MD_SRC=egov-overview.md install.md setup.md egov-overview.md install.md setup.md configuration.md using.md create-virtual.md examples.md contact.md devel.md vmm-manual.md egov-detailed.md

#
# Generated docs
#
GEN_DIR=generated-files/
EGOV_MD=$(GEN_DIR)/egov-manual.md
DEVEL_MD=$(GEN_DIR)/vmm-manual.md

GEN_SRC= $(DEVEL_MD) $(EGOV_MD)
PDF_FILES=$(GEN_SRC:.md=.pdf)
HTML_FILES=$(GEN_SRC:.md=.html)
MANUALS=$(PDF_FILES) $(HTML_FILES)

#
# Rules for pdf and html generation
#
%.pdf:%.md
	pandoc --section-divs -N --chapters -o $@ $<

%.html:%.md
	pandoc -s -S --toc -o $@ $<


$(EGOV_MD):
	-mkdir -p $(GEN_DIR)
	cp egov-manual.md $@
	cat  egov-overview.md  >> $@ 
	cat  install.md        >> $@ 
	cat  setup.md          >> $@ 
	cat  configuration.md  >> $@ 
	cat  using.md          >> $@ 
	cat  egov-detailed.md  >> $@ 
	cat  create-virtual.md >> $@
	cat  examples.md       >> $@
	cat  contact.md        >> $@

$(DEVEL_MD):
	-mkdir -p $(GEN_DIR)
	cp vmm-manual.md      $@
	cat  install.md       >> $@ 
	cat  devel.md         >> $@ 
	cat  contact.md       >> $@

pdf: $(PDF_FILES)

$(PDF_FILES): $(GEN_SRC)
$(HTML_FILES): $(GEN_SRC)

all: $(PDF_FILES) $(HTML_FILES)

clean:
	@-rm -fr $(PDF_FILES)  $(GEN_DIR)

install: $(MANUALS)
	-mkdir -p $(SHARE_DIR)/doc/
	cp $(MANUALS) $(SHARE_DIR)/doc/

